# config.yaml (Final Simplified Content)
session:
  - name: "auth"
    data:
      username: "admin"
      password: "juniper@123"
  - name: "login"
    endpoint: "/ConfigurationManager/v1/objects/sessions"
    method: "POST"
    data:
      sessionid: "sessionId"
      token: "token"
  - name: "logout"
    endpoint: "/ConfigurationManager/v1/objects/sessions/{sessionid}"
    method: "DELETE"

components:
  - name: "information"
    endpoint: "/ConfigurationManager/v1/objects/storages"
    metrics:
    - name: "information"
      help: "Basic information about the SAN device"
      type: "gauge"
      json_path: "data.0.serialNumber"
      labels:
      - name: "SerialNumber"
        json_path: "data.0.serialNumber"
      - name: "StorageDeviceID"
        json_path: "data.0.storageDeviceId"
      - name: "Model"
        json_path: "data.0.model"
    - name: "information_details"
      help: "Detail information about the SAN device"
      type: "gauge"
      json_path: "data.0.serialNumber"
      labels:
      - name: "SerialNumber"
        json_path: "data.0.serialNumber"
      - name: "StorageDeviceID"
        json_path: "data.0.storageDeviceId"
      - name: "CTLIP1"
        json_path: "data.0.ctl1Ip"
      - name: "CTLIP2"
        json_path: "data.0.ctl2Ip"
  - name: "version"
    endpoint: "/ConfigurationManager/configuration/version"
    metrics:
    - name: "version_information"
      help: "Firmware version of the SAN device"
      type: "gauge"
      json_path: "apiVersion"
      labels:
      - name: "version"
        json_path: "apiVersion"
      - name: "product"
        json_path: "productName"
  - name: "node"
    endpoint: "/ConfigurationManager/v1/objects/components/instance"
    metrics:
    - name: "driveboxes_status"
      help: "Status of the SAN drive boxes"
      type: "gauge"
      json_path: "driveBoxes.#.location"
      labels:
      - name: "location"
        json_path: "driveBoxes.#.location"
      - name: "led"
        json_path: "driveBoxes.#.led"
    - name: "ctls_temperature"
      help: "SAN controller temperature"
      type: "gauge"
      json_path: "ctls.#.temperature"
      labels:
      - name: "location"
        json_path: "ctls.#.location"
      - name: "status"
        json_path: "ctls.#.status"
      - name: "temperatureStatus"
        json_path: "ctls.#.temperatureStatus"
      - name: "type"
        json_path: "ctls.#.type"
    - name: "power_consumption"
      help: "Power consumption of the SAN device"
      type: "gauge"
      json_path: "power.powerConsumption"
    - name: "cache_memories"
      help: "Cache memories of the SAN device"
      type: "gauge"
      json_path: "cacheMemories.#.cacheSize"
      labels:
      - name: "location"
        json_path: "cacheMemories.#.location"
      - name: "status"
        json_path: "cacheMemories.#.status"
    - name: "cache_flash_memories"
      help: "Cache flash memories of the SAN device"
      type: "gauge"
      json_path: "cacheFlashMemories.#.status"
      labels:
      - name: "location"
        json_path: "cacheFlashMemories.#.location"
      - name: "status"
        json_path: "cacheFlashMemories.#.status"
      - name: "type"
        json_path: "chbs.#.type"
    - name: "chbs"
      help: "Status of the SAN CHBs"
      type: "gauge"
      json_path: "chbs.#.status"
      labels:
      - name: "location"
        json_path: "chbs.#.location"
      - name: "status"
        json_path: "chbs.#.status"
      - name: "type"
        json_path: "chbs.#.type"
    - name: "dkbs"
      help: "Status of the SAN DKBs"
      type: "gauge"
      json_path: "dkbs.#.status"
      labels:
      - name: "location"
        json_path: "dkbs.#.location"
      - name: "status"
        json_path: "dkbs.#.status"
      - name: "type"
        json_path: "dkbs.#.type"
    - name: "sfps"
      help: "Status of the SAN SFPs"
      type: "gauge"
      json_path: "sfps.#.status"
      labels:
      - name: "portId"
        json_path: "sfps.#.portId"
      - name: "status"
        json_path: "sfps.#.status"
      - name: "type"
        json_path: "sfps.#.type"
      - name: "speed"
        json_path: "sfps.#.speed"
      - name: "portCondition"
        json_path: "sfps.#.portCondition"
    - name: "bkmfs"
      help: "Status of the SAN BKMFs"
      type: "gauge"
      json_path: "bkmfs.#.status"
      labels:
      - name: "location"
        json_path: "bkmfs.#.location"
      - name: "status"
        json_path: "bkmfs.#.status"
    - name: "fans"
      help: "Status of the SAN fans"
      type: "gauge"
      json_path: "fans.#.status"
      labels:
      - name: "location"
        json_path: "fans.#.location"
      - name: "status"
        json_path: "fans.#.status"
  - name: "pools"
    endpoint: "/ConfigurationManager/v1/objects/pools"
    metrics:
    - name: "pool_availableVolumeCapacity"
      help: "Available volume capacity of the storage pool"
      type: "gauge"
      json_path: "data.#.availableVolumeCapacity"
      labels:
      - name: "name"
        json_path: "data.#.poolName"
      - name: "id"
        json_path: "data.#.poolId"
      - name: "type"
        json_path: "data.#.poolType"
      - name: "status"
        json_path: "data.#.poolStatus"
    - name: "pool_availablePhysicalVolumeCapacity"
      help: "Available physical volume capacity of the storage pool"
      type: "gauge"
      json_path: "data.#.availablePhysicalVolumeCapacity"
      labels:
      - name: "name"
        json_path: "data.#.poolName"
      - name: "id"
        json_path: "data.#.poolId"
      - name: "type"
        json_path: "data.#.poolType"
      - name: "status"
        json_path: "data.#.poolStatus"
    - name: "pool_totalPoolCapacity"
      help: "Total capacity of the storage pool"
      type: "gauge"
      json_path: "data.#.totalPoolCapacity"
      labels:
      - name: "name"
        json_path: "data.#.poolName"
      - name: "id"
        json_path: "data.#.poolId"
      - name: "type"
        json_path: "data.#.poolType"
      - name: "status"
        json_path: "data.#.poolStatus"
    - name: "pool_totalPhysicalCapacity"
      help: "Total capacity of the storage pool - physical"
      type: "gauge"
      json_path: "data.#.totalPhysicalCapacity"
      labels:
      - name: "name"
        json_path: "data.#.poolName"
      - name: "id"
        json_path: "data.#.poolId"
      - name: "type"
        json_path: "data.#.poolType"
      - name: "status"
        json_path: "data.#.poolStatus"
  - name: "drives"
    endpoint: "/ConfigurationManager/v1/objects/drives"
    metrics:
    - name: "drive_total_capacity"
      help: "Total capacity of the SAN drives"
      type: "gauge"
      json_path: "data.#.totalCapacity"
      labels:
      - name: "id"
        json_path: "data.#.driveLocationId"
      - name: "serialnumber"
        json_path: "data.#.serialNumber"
      - name: "status"
        json_path: "data.#.status"
      - name: "type"
        json_path: "data.#.driveTypeName"
      - name: "usage"
        json_path: "data.#.usageType"
      - name: "speed"
        json_path: "data.#.driveSpeed"
  - name: "total_capacity"
    endpoint: "/ConfigurationManager/v1/objects/total-capacities/instance"
    metrics:
    - name: "internal_total_capacity"
      help: "Total internal capacity of the SAN device"
      type: "gauge"
      json_path: "internal.totalCapacity"
    - name: "external_total_capacity"
      help: "Total external capacity of the SAN device"
      type: "gauge"
      json_path: "external.totalCapacity"
    - name: "total_capacity"
      help: "Overall total capacity of the SAN device"
      type: "gauge"
      json_path: "total.totalCapacity"
    - name: "internal_freespace_capacity"
      help: "Total internal capacity of the SAN device"
      type: "gauge"
      json_path: "internal.freeSpace"
    - name: "external_freespace_capacity"
      help: "Total external capacity of the SAN device"
      type: "gauge"
      json_path: "external.freeSpace"
    - name: "total_freespace"
      help: "Overall total capacity of the SAN device"
      type: "gauge"
      json_path: "total.freeSpace"
  - name: "alerts"
    endpoint: "/ConfigurationManager/v1/objects/alerts?type=DKC&count=50"
    metrics:
    - name: "storage_dkc_alerts"
      help: "SAN Storage DKC Alerts"
      type: "gauge"
      json_path: "data.#.alertId"
      labels:
      - name: "eventtime"
        json_path: "data.#.occurenceTime"
      - name: "level"
        json_path: "data.#.errorLevel"
      - name: "section"
        json_path: "data.#.errorSection"
      - name: "detail"
        json_path: "data.#.errorDetail"
      - name: "location"
        json_path: "data.#.location"

