{{- range .Values.instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: san-exporter
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .servicePort }}
        volumeMounts:
        - name: config-volume
          mountPath: /san-exporter/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: {{ .name }}-config
---
{{- end }}
